name: Build BlackAddons

on:
  pull_request:
    branches: [ "master", "main", "1.21.10", "1.21.11" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '9.2.1'
          arguments: build

      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: BlackAddons-Mod
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
            !build/libs/*-dev.jar

      - name: Upload Sources Jar
        uses: actions/upload-artifact@v4
        with:
          name: BlackAddons-Sources
          path: build/libs/*-sources.jar
